[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "edgartoolsREW"
description = 'One of the nicest looking EDGAR libraries out there'
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["sec", "edgar", "filings", "company", "python", "finance", "financial", "reports"]
authors = [
  { name = "Dwight Gunning", email = "dgunning@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "httpx>=0.23.1",
  "pandas>=1.1.5",
  "pyarrow>=9.0.0",
  "beautifulsoup4>=4.10.0",
  "lxml>=4.4",
  "rich>=12.6.0",
  "fastcore>=1.5.20",
  "humanize>=4.0.0",
  "charset-normalizer>2.1.1",
  "markdownify>0.11.0",
  "retry>=0.9.2",
  "textdistance[extras]>=4.5.0",
  "rank_bm25==0.2.1"
]
dynamic = ["version"]

[project.urls]
Documentation = "https://dgunning.github.io/edgartools/"
Issues = "https://github.com/dgunning/edgartools/issues"
Source = "https://github.com/dgunning/edgartools"

[tool.hatch.version]
path = "edgar/__about__.py"

[tool.hatch.build]
include = [
  "edgar/*.py",
  "edgar/data/*",
]

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
  "pytest-env",
  "pyinstrument",
  "ruff",
  "jupyter",
  "mkdocs",
  "mkdocstrings[python]",
  "mkdocs-material"
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=edgar --cov=tests {args}"
no-cov = "cov --no-cov {args}"
lint = "ruff edgar"

[tool.hatch.envs.test]
dependencies = [
  "pytest",
  "pytest-cov",
  "pytest-env",
]

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "edgar/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
line-length = 120

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
env = [
    "EDGAR_IDENTITY=Dev Gunning developer-gunning@gmail.com",
]

